### ISSUE TITLE
Contact Information when creating organizations

### ISSUE THREAD

**Issue by peterpaints** [CodeForAfricaLabs/ckan#11]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
When adding an organization, I should be able to add contact information, for instance an email address, a website, social media pages, etc.
The idea is for there to be a `contact dataset owner`, or `contact organization` button, when browsing datasets/organizations.

### Please describe the actual behaviour
The 'add organization' form currently has only three fields: name, description and image url.

### What steps can be taken to reproduce the issue? 
When logged in, click on "Add organization"

**Comment by DavidLemayian** [comment]
Currently the markdown formatting helps keep things simple and organizations can add links to wherever else in the description. We're also not using 2.7.0.
