### ISSUE TITLE
Add search capability for resources within datasets

### ISSUE THREAD

**Issue by edmondatto** [CodeForAfricaLabs/ckan#12]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
A user should be able to search for a specific resource within a dataset

### Please describe the actual behaviour
Currently, there's no provision for searching for a resource within a dataset

### What steps can be taken to resolve the issue? 
Add search capability for resources within datasets

**Comment by DavidLemayian** [comment]
@edmondatto Definitely been discussed in CKAN forum / issues. You should look at what they've said about the challenges of indexing datasets are.
