### ISSUE TITLE
Improve search across CKAN by adding autocomplete

### ISSUE THREAD

**Issue by edmondatto** [CodeForAfricaLabs/ckan#15]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
A user should get auto-complete suggestions based on available results as well as search history (both a particular user's past searches as well as most frequently searched queries by all users) when entering a search query

### Please describe the actual behaviour
Currently, a user gets no assistance when entering a search query

### What steps can be taken to resolve the issue? 
Add support for auto-complete when entering a search query based on available results as well as search history (both a particular user's past searches as well as most frequently searched queries by all users)

**Comment by DavidLemayian** [comment]
Autocomplete can be a very resource hungry endeavor if not done well. So I'd say we need a detailed spec on approach before moving forward with this.

**Comment by DavidLemayian** [comment]
Hi @edmondatto. Having thought through this some more over the weekend, return on investment for this feature is too high for us and we'd therefore opt not to work on it. You're welcome to create an extension/plugin that achieves it though and we'll be happy to look it over.
