### ISSUE TITLE
User should be able to upload their profile picture

### ISSUE THREAD

**Issue by RayNjeri** [CodeForAfricaLabs/ckan#17]
### CKAN Version if known (or site URL)
2.7.1

### Please describe the expected behaviour
user should be able to upload a profile picture aside from being redirected into creating a gravator.

### Please describe the actual behaviour
user gets redirected to creating a gravator.

### What steps can be taken to reproduce the issue? 
add an upload profile picture button aside from the redirection

**Comment by DavidLemayian** [comment]
Not a desired action.
