### ISSUE TITLE
Notify users when they are added to a group or organization

### ISSUE THREAD

**Issue by WNjihia** [CodeForAfricaLabs/ckan#19]
### CKAN Version if known (or site URL)
CKAN 2.7.0a

### Please describe the expected behaviour
A user should be notified on the news feed when they have been added as a member to an organization or group

### Please describe the actual behaviour
The user is added to the organization/group but they are not notified that they have been added as a member

**Comment by DavidLemayian** [comment]
That's a good idea. Let's have this issue in CKAN core - https://github.com/ckan/ckan/issues
