### ISSUE TITLE
Add feature to allow registration through existing social media and email accounts

### ISSUE THREAD

**Issue by Andretalik** [CodeForAfricaLabs/ckan#2]
### CKAN Version if known (or site URL)
Ckan version 2.7.0

### Please describe the expected behaviour
A new user should be able to register and login using relevant accounts e.g: Github, Google.

### Please describe the actual behaviour
The new user has to manually enter their names and passwords as well as their email accounts as well.

### What steps can be taken to reproduce the issue? 
Attempt logging in on any ckan instance.

**Comment by DavidLemayian** [comment]
@Andretalik This should actually work independent of the CKAN repo as a "plugin" so that other CKAN deployments can easily use it. So let's work of the repo here instead to achieve this - https://github.com/CodeForAfricaLabs/ckanext-socialite
