### ISSUE TITLE
Notify users when they are removed as members from a group or organization

### ISSUE THREAD

**Issue by WNjihia** [CodeForAfricaLabs/ckan#20]
### CKAN Version if known (or site URL)
CKAN 2.7.0a

### Please describe the expected behaviour
A user should be notified on the news feed when they have been removed as a member from an organization or group

### Please describe the actual behaviour
The user is removed as a member from an organization/group but they are not notified that they have been removed as a member

**Comment by DavidLemayian** [comment]
This is related to the other issue you created. Let's do the same.
