### ISSUE TITLE
Bug: Datarequest tab missing when using openAfrica Extension.

### ISSUE THREAD

**Issue by daumie** [CodeForAfricaLabs/ckan#21]
### CKAN Version if known (or site URL)
2.7.0a

### Please describe the expected behavior
A user should be able to interact with the datarequests tab when using the *openAfrica extension*.

### Please describe the actual behavior
When using the *openafrica extension*. The *datarequest extension*  is inaccessible though active.

### What steps can be taken to reproduce the issue? 
- Install the *openafrica extension* 
- Install the *datarequest extension*
- The  *datarequest* does not show, but when  *openafrica extension* is ommitted. The tab appears.

**Comment by DavidLemayian** [comment]
Related to https://github.com/CodeForAfrica/ckanext-openafrica/issues/26
