### ISSUE TITLE
Language switcher doesn't work.

### ISSUE THREAD

**Issue by RayNjeri** [CodeForAfricaLabs/ckan#5]
### Please describe the expected behaviour
when switching to a different language the content should change according to the language selected.

### Please describe the actual behaviour
instead of the change of language you get a 404 error.

### What steps can be taken to reproduce the issue? 
ensure all languages work as expected.

**Comment by dmkitui** [comment]
I would like to partner with you on this issue. Looks related to this other issue: https://github.com/ckan/ckan/issues/3757

**Comment by RayNjeri** [comment]
yes they are similar only that the issue was closed before being resolved

**Comment by DavidLemayian** [comment]
Closing this in favor of working on it there.
