### ISSUE TITLE
Add dataset button on groups page

### ISSUE THREAD

**Issue by Mercy-Muchai** [CodeForAfricaLabs/ckan#6]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
When you create a group, the page shows there are no datasets on the group. There is no **Add Dataset** button on this page yet they exist on other pages

### Please describe the actual behaviour
When I create a group, I should be able to add datasets to the group

### What steps can be taken to resolve the issue? 
Add the existing button to the page and ensure it adds to the specific group

**Comment by DavidLemayian** [comment]
Thanks for this @Mercy-Muchai. Let's have this on https://github.com/CodeForAfrica/ckanext-openafrica instead as we intend to use only the most vanilla instance of CKAN in deployment and not make any changes to core code.

Ref #22

**Comment by Mercy-Muchai** [comment]
@DavidLemayian 
Question: On https://github.com/CodeForAfrica/ckanext-openafrica, the templates do not touch on the groups link at all. This means I may have to make it redundant by adding it. Please advise.
