### ISSUE TITLE
search dataset by any string vs full name

### ISSUE THREAD

**Issue by Mercy-Muchai** [CodeForAfricaLabs/ckan#7]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
I should be able to type any string and get results for datasets with the string in the name

### Please describe the actual behaviour
When searching for a dataset in a given list, it only finds result of full words that exist in a named dataset. 

### What steps can be taken to resolve the issue? 
On the codebase, implement either an autocomplete or change the search logic to implement the expected behaviour

**Comment by DavidLemayian** [comment]
This might be a solr tweak. But also we are using 2.6.x not 2.7 yet.

**Comment by Mercy-Muchai** [comment]
@DavidLemayian Please clarify on **This might be a solr tweak**. Does this mean it could be resolved on solr?
