### ISSUE TITLE
Bug: Adding Image Views to Dataset

### ISSUE THREAD

**Issue by Mercy-Muchai** [CodeForAfricaLabs/ckan#8]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
A user should be able to add views to a dataset in image form or PDF form

### Please describe the actual behaviour

When adding an image view to a dataset, there is an internal server error: **TemplateNotFound: image-form.html**

**Comment by DavidLemayian** [comment]
Again, possibly teething for 2.7.0. You can flag on https://github/ckan/ckan but we aren't using this version of CKAN. Please refer to https://github.com/CodeForAfricaLabs/openAFRICA
