### ISSUE TITLE
"Follow System" requires page reload to update number of followers.

### ISSUE THREAD

**Issue by andela-dhaniabelega** [CodeForAfricaLabs/ckan#9]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
When a user follows a dataset, a group, or  another user, the follow count (or number of followers) should be updated instantly.

### Please describe the actual behaviour
When a user follows a dataset, a group, or another user, a page reload is required for the number of followers to be updated.

### What steps can be taken to reproduce the issue? 
Navigate to the data sets page by clicking on "Datasets" on the navigation bar. Choose a dataset (or create one if none exists). Click on the Follow button on the side navigation. The number of followers won't be updated until you reload the page.

**Comment by DavidLemayian** [comment]
We're not using CKAN 2.7.0 so might be something you want to add to the issues at https://github.com/ckan/ckan
